stages:
  - build
  - test

build:
  image: gcc
  stage: build
  artifacts:
    paths:
      - lib/libmy.a
      - include/my.h
  script: make

test:
  stage: test
  image: ethaligan/epitech-c
  script:
    - make test
    - gcovr -s
  coverage: '/lines: \d+\.\d+/'

