stages:
  - build
  - test

build:
  image: gcc
  stage: build
  artifacts:
    paths:
      - lib/libmy.a
      - include/my.h
  script: make

test:
  stage: test
  image: itiut/gcc-criterion
  script:
    - make test

