stages:
  - build
  - tests

.base:
  only:
    changes:
      - src/**/*
      - tests/**/*
      - include/**/*

build:
  stage: build
  extends: .base
  image: gcc
  artifacts:
    paths:
      - lib/libmy.a
      - include/my.h
  script: make

norm:
  stage: tests
  extends: .base
  image: ethaligan/epitech-c
  allow_failure: yes
  script:
    - normez

test:
  stage: tests
  extends: .base
  image: ethaligan/epitech-c
  script:
    - make test
    - gcovr -s
  coverage: '/lines: \d+\.\d+/'


