stages:
  - build
  - test

build:
  image: gcc
  stage: build
  artifacts:
    paths:
      - lib/libmy.a
      - include/my.h
  script: make

test:
  stage: test
  image: alpine
  before_script:
    - scripts/setup
  script:
    - make test
    - gcovr -sp
  coverage: '/lines: \d+.\d+/'
