stages:
  - build
  - test

build:
  image: gcc
  stage: build
  artifacts:
    paths:
      - lib/libmy.a
  script: make

test:
  stage: test
  image: arthurphilippe/epitech-c-cpp-plain
  script:
    - make test
    - gcovr -sp
  coverage: '/lines: \d+.\d+/'

