stages:
  - build
  - test

build:
  image: gcc
  stage: build
  artifacts:
    paths:
      - lib/libmy.a
  script: make

test:
  stage: test
  image: itiut/gcc-criterion
  before_script:
    - apt-get install -y --no-install-recommends gcovr
  script:
    - make test
    - gcovr -sp
  coverage: '/lines: \d+.\d+/'

