#!/usr/bin/env sh

# Alpine
apk add gcc make cmake musl-dev gcovr git g++

# Criterion
git clone --recursive -b master https://github.com/Snaipe/Criterion criterion
cd criterion
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib ..
make -j
make install
cd ../../
rm -rf criterion
