name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: adrienbrignon/epitech-c
    steps:
      - uses: actions/checkout@v2
      - name: Execute unit tests
        run: make test
